### PR TITLE
Update README.md and update to latest WDK

### PR DESCRIPTION
**Pull request by Oxalin**
Clarified and fixed README.md.
Updated Windows driver kit requirement to latest version (10.0.1763). Previous version should still work, but you will need to change the version in the VS projects.

### CODE REVIEW

**Comment by cezuni** [comment]
I had messed up commit history by simply merging @Oxalin pull requests. Sorry for my faults. I'll do rebase and merge. b16d2c8 is cherry-picked and pushed to master branch but 831a2b1 needs more time.

**Comment by cezuni** [comment]
@Oxalin : Can you check cf76164970bcee5a6e633dfeea242f10ab033515 on dev branch ? It is a squashed commit from your 831a2b15ca1e01e617d55537c9d86ac83d450b4c. Disappointingly, $(LatestTargetPlatformVersion) is not working in userspace projects but kernel projects are OK. This seems to be a sort of VS bug. So fixed SDK version for userland projects should be specified. Anyway, it would be desirable that latest SDK & WDK are supported. I've confirmed that usbip-win is successfully built with old SDK(10.0.17134). I will merge to master if  you confirm.

**Comment by Oxalin** [comment]
As a follow up, I have not had a look at that commit yet.

I've been working on bringing a new feature available under Linux in the
little time I had in the last weeks: port enumeration. I'll keep you posted
about it soon... And I'll have a look at the commit. ;)

Alexandre

**Comment by koudis** [comment]
@cezuni  @Oxalin 
I think that "Compile with Latest WDK and SDK" is acceptable.

Userspace utilities are compiled by v142 (https://github.com/cezuni/usbip-win/commit/fc79b7b80802b6fe7e565b424ad2c0382e146f41). V142 compiller needs  SDK version >= 10.0.17*.
Drivers are compiled by WDK 10.0 1903 which needs SDK 10.0.18*.

I hope that WDK is written correctly and if they bring some breaking changes it does not break old WDK api.

I suggest use "Lastest SDK and WDK" and add note with tested vesions (SDK >=10.0.17*).
Second option is to use CMake or simmilar tool for dependency managing (but T am not sure if there is a correct support for WDK).

**Comment by koudis** [comment]
Waaw, the WDK has a static free version (called Enterprise WDK)
https://docs.microsoft.com/cs-cz/windows-hardware/drivers/download-the-wdk

I guest that rewrite project to CMake brings many advantages
- Control the exact version of SDK/WDK (or minimum needed)
- Control around signing
- Simple packagaging and releasing

**Comment by cezuni** [comment]
I updated [dev branch](https://github.com/cezuni/usbip-win/tree/dev) forcefully. This branch replaces fixed sdk versions with (LatestTargetPlatformVersion) in all userland projects. VS 2019 treats well $(LatestTargetPlatformVersion). 
Although usbip-win recommends an up-to-date build environment, old SDK/WDK and VS2017 seem to have no problem to build. I have tested with some versions as noted in README.md on dev branch.

**Comment by cezuni** [comment]
@koudis : Your CMake idea is very good. However, is it possible that CMake is integrated with VS. Even though it is a command-only build tool, CMake can be a versatile additional build tool. In my opinion, CMake build process can be adopted independently of an existing VS build.

**Comment by koudis** [comment]
@cezuni 
It's not effective maintain CMake and own .sln in one project (CMake can generate .sln etc)
CMake has a simple GUI which can by used instead of raw command line.
In case we can create simple .ps1 script which runs CMake and generates .sln file

I will do some research... and see how difficult is to move/add project to CMake.

**Comment by cezuni** [comment]
> I updated dev branch forcefully. This branch replaces fixed sdk versions with (LatestTargetPlatformVersion) in all userland projects. VS 2019 treats well $(LatestTargetPlatformVersion).
Although usbip-win recommends an up-to-date build environment, old SDK/WDK and VS2017 seem to have no problem to build. I have tested with some versions as noted in README.md on dev branch.

This work has been merged into the master branch. I'll close this PR and remove dev branch.

**Comment by koudis** [comment]
After #48 I try to create CMAke projec tprototype for USBIP Project.

**Pull request closed without merging**
